### PR TITLE
Port to core2.1

### PR DESCRIPTION
**Pull request by merqlove**
Updated PL #6 by @Gimly:

- Upgraded to .NetCore 2.1
- Updated HttpClient, yes HttpFactory pattern
- Added serviceCollection for easier installation on .net core projects.
- Added Makefile to build projects
- Updated dependencies

### CODE REVIEW

**Comment by ReyOrtiz** [comment]
I'm waiting for this PR to be merged. Does @cristipufu still maintain this? Haven't seen much activity for while.

**Comment by cristipufu** [comment]
I will publish it to NuGet in a few days.

Thanks @Gimly & @merqlove for your awesome work.

**Comment by ReyOrtiz** [comment]
Hi @cristipufu, just wondering if you have a target date to publish to NuGet. I'm in the process of migrating to .net core and this is one of the pieces is holding me back.

Thanks!

**Comment by ReyOrtiz** [comment]
Hello @cristipufu, sorry to ask again. Do you still plan to publish to NuGet? Thanks

**Pull request merged**
